const { Features } = require("../models");

const seedFeatures = () => Features.bulkCreate(featuresData);

const featuresData = [
  {
    num_guests: 4,
    num_beds: 3,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: false,
    waterfront: true,
    category_id: 6,
    location_id: 1, // Argosy Trailer
  },
  {
    num_guests: 9,
    num_beds: 6,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 2,
    location_id: 2, // The Barn
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 2,
    location_id: 3, // Birch Yurt
  },
  {
    num_guests: 3,
    num_beds: 2,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 2,
    location_id: 4, // The Bird House
  },
  {
    num_guests: 6,
    num_beds: 3,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 2,
    location_id: 5, // Captain's Quarters
  },
  {
    num_guests: 8,
    num_beds: 3,
    wifi: false,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 2,
    location_id: 6, // Fern Alley
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 2,
    location_id: 7, // The Lookout
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: false,
    waterfront: false,
    category_id: 2,
    location_id: 8, // Frog Hollow
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: false,
    waterfront: false,
    category_id: 6,
    location_id: 9, // Vintage Trailer
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: false,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 2,
    location_id: 10, // Robin's Nest
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: false,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 2,
    location_id: 11, // Deer Run
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: false,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: false,
    shower: true,
    waterfront: false,
    category_id: 2,
    location_id: 12, // Ma'iingan - Loup
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: false,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 2,
    location_id: 13, // Baker Cabin
  },
  {
    num_guests: 3,
    num_beds: 2,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 2,
    location_id: 14, // The Flora Cozy Cabin
  },
  {
    num_guests: 3,
    num_beds: 2,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 2,
    location_id: 15, // The Fauna Cozy Cabin
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: false,
    electricity: true,
    shower: false,
    waterfront: false,
    category_id: 4,
    location_id: 16, // The Birches
  },
  {
    num_guests: 5,
    num_beds: 4,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: false,
    electricity: true,
    shower: false,
    waterfront: true,
    category_id: 4,
    location_id: 17, // The Quarry View
  },
  {
    num_guests: 5,
    num_beds: 4,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: false,
    electricity: true,
    shower: false,
    waterfront: true,
    category_id: 4,
    location_id: 18, // The Mills & the Carriages
  },
  {
    num_guests: 6,
    num_beds: 4,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: false,
    electricity: true,
    shower: false,
    waterfront: true,
    category_id: 4,
    location_id: 19, // The Pines
  },
  {
    num_guests: 6,
    num_beds: 4,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: false,
    electricity: true,
    shower: false,
    waterfront: true,
    category_id: 4,
    location_id: 20, // The Maples
  },
  {
    num_guests: 7,
    num_beds: 5,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: false,
    electricity: true,
    shower: false,
    waterfront: true,
    category_id: 4,
    location_id: 21, // The Meadows
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: true,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 2,
    location_id: 22, // Mirror Cabin The Orchard
  },
  {
    num_guests: 2,
    num_beds: 2,
    wifi: true,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 2,
    location_id: 23, // Yeomans by the Caves Bunkie
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 2,
    location_id: 24, // Cabin on the Falls
  },
  {
    num_guests: 5,
    num_beds: 3,
    wifi: false,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 2,
    location_id: 25, // The Owl's Nest A-Frame
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: true,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 2,
    location_id: 26, // Orchard Cabin
  },
  {
    num_guests: 10,
    num_beds: 4,
    wifi: true,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 2,
    location_id: 27, // Nova Glamping Cabin
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: false,
    cell_service: true,
    fireplace: true,
    kitchen: false,
    electricity: false,
    shower: false,
    waterfront: false,
    category_id: 2,
    location_id: 28, // Meridian 63 Cabins
  },
  {
    num_guests: 6,
    num_beds: 4,
    wifi: true,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 2,
    location_id: 29, // Island View Log Cabin
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: false,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 2,
    location_id: 30, // Ome Pod
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: true,
    cell_service: true,
    fireplace: false,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 1,
    location_id: 31, // Corresponding to Heaven
  },
  {
    num_guests: 666,
    num_beds: 0,
    wifi: false,
    cell_service: false,
    fireplace: true, // Always on!
    kitchen: false,
    electricity: false,
    shower: false,
    waterfront: false,
    category_id: 2,
    location_id: 32, // Corresponding to Hell
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: true,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 3,
    location_id: 33, // The Brook
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: true,
    cell_service: false,
    fireplace: true,
    kitchen: false,
    electricity: false,
    shower: false,
    waterfront: false,
    category_id: 3,
    location_id: 34, //Atlantic Dome
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: true,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 3,
    location_id: 35, //Hubbards Domes
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: true,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 3,
    location_id: 36, //Port Wade
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: true,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: false,
    category_id: 3,
    location_id: 37, // Fundy Dome
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: true,
    cell_service: false,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: false,
    waterfront: false,
    category_id: 3,
    location_id: 38, // Northern Spy
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: true,
    cell_service: false,
    fireplace: false,
    kitchen: false,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 3,
    location_id: 39, // Geodesic Dome
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: true,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 3,
    location_id: 40, // Luxury Lakeside
  },
  {
    num_guests: 4,
    num_beds: 3,
    wifi: true,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 3,
    location_id: 41, //Shoreline Retreat
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: true,
    cell_service: false,
    fireplace: true,
    kitchen: false,
    electricity: false,
    shower: false,
    waterfront: true,
    category_id: 3,
    location_id: 42, //Hilltop
  },
  {
    num_guests: 4,
    num_beds: 2,
    wifi: false,
    cell_service: false,
    fireplace: true,
    kitchen: false,
    electricity: false,
    shower: false,
    waterfront: false,
    category_id: 3,
    location_id: 43, //Moonshine
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: true,
    cell_service: true,
    fireplace: true,
    kitchen: true,
    electricity: true,
    shower: true,
    waterfront: true,
    category_id: 3,
    location_id: 44, //Oceanfront
  },
  {
    num_guests: 2,
    num_beds: 1,
    wifi: true,
    cell_service: true,
    fireplace: true,
    kitchen: false,
    electricity: false,
    shower: false,
    waterfront: true,
    category_id: 3,
    location_id: 45, // treetop
  },
];

module.exports = seedFeatures;
